if {$argc < 4} {
  puts "usage: export_current_project_scripts.tcl <project.xpr> <out_dir> <apply:0|1> <root_dir> ?ip_dir?"
  exit 2
}

set project_file [file normalize [lindex $argv 0]]
set out_dir      [file normalize [lindex $argv 1]]
set apply        [lindex $argv 2]
set root_dir     [file normalize [lindex $argv 3]]
if {$argc >= 5} {
  set ip_dir [file normalize [lindex $argv 4]]
} else {
  set ip_dir [file normalize [file join $root_dir "lib" "ip"]]
}

proc t510_path_is_under {path root} {
  set path [string map {\\ /} [file normalize $path]]
  set root [string trimright [string map {\\ /} [file normalize $root]] /]
  return [expr {$path eq $root || [string first "${root}/" $path] == 0}]
}

proc t510_relative_to {path root} {
  set path [string map {\\ /} [file normalize $path]]
  set root [string trimright [string map {\\ /} [file normalize $root]] /]
  if {$path eq $root} {
    return ""
  }
  return [string range $path [expr {[string length $root] + 1}] end]
}

proc t510_normalized_export_relpath {path root} {
  set nf [file normalize $path]
  if {[t510_path_is_under $nf $root]} {
    set rel [t510_relative_to $nf $root]
    set rel [string map {\\ /} $rel]
    set marker "/"
    foreach dir [list "top/" "xdc/" "lib/ip/"] {
      set needle "${marker}${dir}"
      set idx [string first $needle $rel]
      if {$idx >= 0} {
        return [string range $rel [expr {$idx + 1}] end]
      }
      if {[string first $dir $rel] == 0} {
        return $rel
      }
    }
    return $rel
  }
  return ""
}

proc t510_should_export_relpath {rel allowed_exts} {
  set rel [string map {\\ /} $rel]
  if {[string match "vivado/project/*" $rel]} {
    return 0
  }
  if {[string match "scripts/vivado/generated/*" $rel]} {
    return 0
  }
  if {[string match "artifacts/*" $rel]} {
    return 0
  }

  set ext [string tolower [file extension $rel]]

  if {[string match "lib/ip/*" $rel]} {
    return [expr {($ext eq ".xci" && [lsearch -exact $allowed_exts ".xci"] >= 0) ||
                  ($ext eq ".xcix" && [lsearch -exact $allowed_exts ".xcix"] >= 0)}]
  }

  if {[string match "lib/library/*" $rel]} {
    return 0
  }

  return [expr {[lsearch -exact $allowed_exts $ext] >= 0}]
}

proc t510_collect_fileset_relpaths {fileset root allowed_exts} {
  set out [list]
  foreach f [get_files -quiet -of_objects [get_filesets $fileset]] {
    set nf [file normalize $f]
    set rel [t510_normalized_export_relpath $nf $root]
    if {$rel eq ""} {
      continue
    }
    if {![t510_should_export_relpath $rel $allowed_exts]} {
      continue
    }
    lappend out $rel
  }
  return [lsort -unique $out]
}

proc t510_is_bd_generated_ip {path root} {
  set rel [t510_relative_to $path $root]
  set rel [string map {\\ /} $rel]
  return [expr {
    [string match "vivado/project/*/*.srcs/sources_1/bd/*/ip/*" $rel] ||
    [string match "vivado/project/*/*.gen/sources_1/bd/*/ip/*" $rel] ||
    [string match "vivado/project/*/*.cache/ip/*" $rel]
  }]
}

proc t510_stage_project_ip_files {root ip_dir} {
  set out [list]
  foreach f [get_files -quiet -filter {FILE_TYPE == "IP"}] {
    set nf [file normalize $f]
    set ext [string tolower [file extension $nf]]
    if {$ext ne ".xci" && $ext ne ".xcix"} {
      continue
    }

    if {[t510_path_is_under $nf [file join $root "lib" "ip"]]} {
      lappend out [t510_relative_to $nf $root]
      continue
    }

    if {![t510_path_is_under $nf $root]} {
      puts "WARNING: skipping IP outside T510_FNIC tree: $nf"
      continue
    }

    if {[t510_is_bd_generated_ip $nf $root]} {
      continue
    }

    set ip_name [file rootname [file tail $nf]]
    set dest_dir [file join $ip_dir $ip_name]
    set dest_file [file join $dest_dir "${ip_name}${ext}"]
    file mkdir $dest_dir

    if {[file normalize $nf] ne [file normalize $dest_file]} {
      file copy -force $nf $dest_file
      puts "Exported project IP:"
      puts "  $nf"
      puts "  -> $dest_file"
    }

    if {[t510_path_is_under $dest_file $root]} {
      lappend out [t510_relative_to $dest_file $root]
    } else {
      lappend out [string map {\\ /} [file normalize $dest_file]]
    }
  }
  return [lsort -unique $out]
}

proc t510_write_rel_list {fp var_name relpaths} {
  puts $fp "set ${var_name} \[list \\"
  foreach rel $relpaths {
    puts $fp "  \"$rel\" \\"
  }
  puts $fp "\]"
}

proc t510_write_sources_tcl {path source_relpaths ip_relpaths constraint_relpaths} {
  set fp [open $path w]
  puts $fp "# Generated by export_current_project_scripts.tcl from the current Vivado project."
  puts $fp "# Do not edit this file by hand; open the Vivado project, update filesets, then rerun:"
  puts $fp "#   hdl/t510_fnic/scripts/export_current_project_scripts.sh --apply"
  puts $fp ""
  puts $fp "if {!\[info exists root_dir\]} {"
  puts $fp "  set script_dir \[file normalize \[file dirname \[info script\]\]\]"
  puts $fp "  set root_dir   \[file normalize \[file join \$script_dir \"..\" \"..\"\]\]"
  puts $fp "}"
  puts $fp ""
  puts $fp "proc t510_add_rel_files {fileset root_dir relpaths args} {"
  puts $fp "  if {\[llength \$relpaths\] == 0} {"
  puts $fp "    return"
  puts $fp "  }"
  puts $fp "  set files \[list\]"
  puts $fp "  foreach rel \$relpaths {"
  puts $fp "    lappend files \[file join \$root_dir \$rel\]"
  puts $fp "  }"
  puts $fp "  add_files -fileset \$fileset {*}\$args \$files"
  puts $fp "}"
  puts $fp ""
  puts $fp "proc t510_import_rel_ip_files {root_dir relpaths} {"
  puts $fp "  if {\[llength \$relpaths\] == 0} {"
  puts $fp "    return"
  puts $fp "  }"
  puts $fp "  set files \[list\]"
  puts $fp "  foreach rel \$relpaths {"
  puts $fp "    lappend files \[file join \$root_dir \$rel\]"
  puts $fp "  }"
  puts $fp "  import_files -fileset sources_1 \$files"
  puts $fp "}"
  puts $fp ""
  t510_write_rel_list $fp "t510_source_rel_files" $source_relpaths
  puts $fp ""
  t510_write_rel_list $fp "t510_ip_rel_files" $ip_relpaths
  puts $fp ""
  t510_write_rel_list $fp "t510_constraint_rel_files" $constraint_relpaths
  puts $fp ""
  puts $fp "t510_add_rel_files sources_1 \$root_dir \$t510_source_rel_files -norecurse"
  puts $fp "t510_import_rel_ip_files \$root_dir \$t510_ip_rel_files"
  puts $fp "t510_add_rel_files constrs_1 \$root_dir \$t510_constraint_rel_files -norecurse"
  close $fp
}

if {![file exists $project_file]} {
  puts stderr "missing Vivado project: $project_file"
  exit 1
}

file mkdir $out_dir
open_project $project_file

set bd_files [get_files -quiet -filter {FILE_TYPE == "Block Designs"}]
if {[llength $bd_files] != 1} {
  puts stderr "expected exactly one block design, found [llength $bd_files]: $bd_files"
  exit 1
}

set bd_file [lindex $bd_files 0]
open_bd_design $bd_file
set bd_name [get_property NAME [current_bd_design]]

set generated_bd_tcl [file join $out_dir "create_t510_fnic_aurora_bd.tcl"]
set generated_sources_tcl [file join $out_dir "create_t510_fnic_aurora_sources.tcl"]
write_bd_tcl -force $generated_bd_tcl

set source_relpaths [t510_collect_fileset_relpaths sources_1 $root_dir [list ".v" ".sv" ".vh" ".vhd" ".coe"]]
set ip_relpaths [concat \
  [t510_collect_fileset_relpaths sources_1 $root_dir [list ".xci" ".xcix"]] \
  [t510_stage_project_ip_files $root_dir $ip_dir] \
]
set ip_relpaths [lsort -unique $ip_relpaths]
set constraint_relpaths [t510_collect_fileset_relpaths constrs_1 $root_dir [list ".xdc"]]
t510_write_sources_tcl $generated_sources_tcl $source_relpaths $ip_relpaths $constraint_relpaths

set report_file [file join $out_dir "PROJECT_STATE.txt"]
set fp [open $report_file w]
puts $fp "project_file=$project_file"
puts $fp "project_name=[get_property NAME [current_project]]"
puts $fp "project_part=[get_property PART [current_project]]"
puts $fp "top=[get_property top [get_filesets sources_1]]"
puts $fp "block_design=$bd_file"
puts $fp "block_design_name=$bd_name"
puts $fp "generated_bd_tcl=$generated_bd_tcl"
puts $fp "generated_sources_tcl=$generated_sources_tcl"
puts $fp ""
puts $fp "exported_source_rel_files:"
foreach f $source_relpaths {
  puts $fp "  $f"
}
puts $fp ""
puts $fp "exported_ip_rel_files:"
foreach f $ip_relpaths {
  puts $fp "  $f"
}
puts $fp ""
puts $fp "exported_constraint_rel_files:"
foreach f $constraint_relpaths {
  puts $fp "  $f"
}
puts $fp ""
puts $fp "source_files:"
foreach f [lsort [get_files -quiet -of_objects [get_filesets sources_1]]] {
  puts $fp "  $f"
}
puts $fp ""
puts $fp "constraint_files:"
foreach f [lsort [get_files -quiet -of_objects [get_filesets constrs_1]]] {
  puts $fp "  $f"
}
puts $fp ""
puts $fp "ip_files:"
foreach f [lsort [get_files -quiet -filter {FILE_TYPE == "IP"}]] {
  puts $fp "  $f"
}
close $fp

puts "Generated:"
puts "  $generated_bd_tcl"
puts "  $generated_sources_tcl"
puts "  $report_file"

if {$apply eq "1"} {
  set bd_target [file join $root_dir "scripts" "vivado" "create_t510_fnic_aurora_bd.tcl"]
  if {[file exists $bd_target]} {
    set bd_backup "${bd_target}.bak"
    file copy -force $bd_target $bd_backup
    puts "Backup:"
    puts "  $bd_backup"
  }
  file copy -force $generated_bd_tcl $bd_target
  puts "Applied:"
  puts "  $bd_target"

  set sources_target [file join $root_dir "scripts" "vivado" "create_t510_fnic_aurora_sources.tcl"]
  if {[file exists $sources_target]} {
    set sources_backup "${sources_target}.bak"
    file copy -force $sources_target $sources_backup
    puts "Backup:"
    puts "  $sources_backup"
  }
  file copy -force $generated_sources_tcl $sources_target
  puts "Applied:"
  puts "  $sources_target"
} else {
  puts ""
  puts "Review the generated Tcl first. To replace create_t510_fnic_aurora_bd.tcl and create_t510_fnic_aurora_sources.tcl, rerun with --apply."
}

close_project
