BOARD_NAME ?= $(BOARD)
BOARD_DESC ?= $(BOARD) firmware builder
BOARD_DIR ?= $(CURDIR)/board/$(BOARD)
BOARD_BOOT_DIR ?= $(BOARD_DIR)/boot
BOARD_LINUX_DIR ?= $(BOARD_DIR)/linux
BOARD_UBOOT_DIR ?= $(BOARD_DIR)/u-boot
BOARD_BUILDROOT_DIR ?= $(BOARD_DIR)/buildroot

SOC_FAMILY ?= zynqmp
ATF_PLAT ?= $(SOC_FAMILY)
BOOTGEN_ARCH ?= $(SOC_FAMILY)

HW_PROJECT_DIR ?= $(CURDIR)/hdl/$(BOARD)
HW_FILE ?= $(HW_PROJECT_DIR)/system_top.xsa
HW_BIT ?= $(HW_PROJECT_DIR)/system_top.bit

FSBL_PROC ?= psu_cortexa53_0
PMUFW_PROC ?= psu_pmu_0
DT_PROC ?= $(FSBL_PROC)
FSBL_BOOT_PROFILE ?= full
FSBL_DEBUG_LEVEL ?= off
PMUFW_ENABLE_EFUSE_ACCESS ?= 0

CONSOLE_UART ?= 0
CONSOLE_UART_ALT ?= $(if $(filter 0,$(CONSOLE_UART)),1,0)
CONSOLE_TTY ?= ttyPS0
CONSOLE_UART_NODE ?= uart$(CONSOLE_UART)
CONSOLE_UART_ALT_NODE ?= uart$(CONSOLE_UART_ALT)
CONSOLE_PSU_UART ?= psu_uart_$(CONSOLE_UART)
CONSOLE_ATF ?= cadence$(CONSOLE_UART)
CONSOLE_UART_BASE ?= $(if $(filter 0,$(CONSOLE_UART)),0xff000000,0xff010000)
CONSOLE_EARLYCON ?= cdns,mmio,$(CONSOLE_UART_BASE)

FSBL_STDIO ?= $(CONSOLE_PSU_UART)
PMUFW_STDIO ?= $(CONSOLE_PSU_UART)

BUILDROOT_CROSS ?= aarch64-linux-gnu-
BUILDROOT_DEFCONFIG_FILE ?= $(BOARD_BUILDROOT_DIR)/defconfig

LINUX_DEFCONFIG ?= xilinx_zynqmp_defconfig
UBOOT_DEFCONFIG ?= xilinx_zynqmp_zcu102_revA_defconfig
UBOOT_CONFIG_FRAGMENT ?= $(BOARD_UBOOT_DIR)/fragment.config
UBOOT_DTS_NAME ?=
UBOOT_DTS_SOURCE ?= $(if $(UBOOT_DTS_NAME),$(BOARD_UBOOT_DIR)/$(UBOOT_DTS_NAME).dts)

FIT_DESCRIPTION ?= $(BOARD_DESC) Linux FIT image
FIT_KERNEL_LOAD_ADDR ?= 0x00080000
FIT_KERNEL_ENTRY_ADDR ?= 0x00080000

ATF_EXTRA_MAKE_FLAGS ?=
ATF_MAKE_FLAGS ?= ZYNQMP_CONSOLE=$(CONSOLE_ATF) $(ATF_EXTRA_MAKE_FLAGS)

UENV_FILE ?= $(BOARD_BOOT_DIR)/uEnv.txt
SYSTEM_USER_DTSI ?= $(BOARD_LINUX_DIR)/system-user.dtsi
SD_KERNEL_IMAGE_NAME ?= Image
SD_BOOT_IMAGE_NAME ?= BOOT.bin
SD_DTB_NAME ?= devicetree.dtb
SD_RAMDISK_NAME ?= uramdisk.image.gz
SD_BITSTREAM_NAME ?=
BOOT_BIN_INCLUDE_BITSTREAM ?= y

QSPI_TOTAL_SIZE ?= 0x04000000
QSPI_BOOT_OFFSET ?= 0x00000000
QSPI_IMAGE_OFFSET ?= 0x00400000
QSPI_IMAGE_MAX_SIZE ?= 0x02000000
